name             'crf-motd'
maintainer       'Crossroads Foundation Ltd'
maintainer_email 'itdept@crossroads.org.hk'
license          'Apache 2.0'
description      'Installs/Configures crf-motd'
long_description 'Installs/Configures crf-motd'
version          '0.1.0'
issues_url       'https://github.com/crossroads/crf-motd/issues'
source_url       'https://github.com/crossroads/crf-motd'

depends 'motd'
